management:
  endpoints:
    web:
      exposure:
      include: '*'
  info:
    env:
      enabled: true

info:
  application:
    name: ClassicNote
    description: A diary application
    author: PerryJay
    version: '@project.version@'
spring:
  profiles:
    active: prod
